/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package del2;

import org.apache.SNX.SNX;

public class App {

    public static void main(String[] args) {
        System.out.println("hi");
        new SNX();
    }
}
