/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package del2;

import org.apache.SNX.db.Del;


public class App {
    App() {
        new Del().del();

    }
    public static void main(String[] args) {
        new App();
    }
}
